### ISSUE TITLE
Link Documentation Page

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/vscode-piral#11]
We could link the documentation page of the CLI / Piral in the workspace info.

This is similar to #10, however, instead of showing the README (e.g., from GitHub or NPM) we show the docs.piral.io page.

Ideal case: We show the documentation *for the specific version*.

**Comment by iotcloudarchitect** [comment]
Committed, Pushed, Done.
Except for the fact of showing the web page inside VS Code.
Currently, the web page is shown on external web browser.

**Comment by FlorianRappl** [comment]
Alright, thanks for the info.

Landed in `develop`.
