### ISSUE TITLE
Initial Workspace Info

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/vscode-piral#2]
Populate the Piral workspace info with useful information:

- Is the currently opened folder a monorepo, piral, or pilet workspace?
- What is the app shell (incl. version of the app shell)?
- What version of the Piral CLI is used?
- Is this the latest version of the app shell?
- Is this the latest version of the Piral CLI?
- What plugins are used (for the app shell)?
- What dependencies are shared (for a pilet)?

**Comment by iotcloudarchitect** [comment]
The following has been introduced with latest commit:

**For Piral project**
- Piral Name + Version
- Piral CLI Version
- Piral Plugins

**For Pilet project**
- Pilet Name + Version
- App Shell Name + Version
- Piral CLI Version
- Dependencies

Currently missing is:
- Showing information about latest versions of App Shell
- Showing information about latest versions of Piral CLI

It must be specified on how to detect monorepo and what information should be displayed in this case.

**Comment by FlorianRappl** [comment]
Landed in  `develop`.

Great work!
