### ISSUE TITLE
Example launch.json configuration (with preLaunchTask) not working?

### ISSUE THREAD

**Issue by Balfa** [smapiot/vscode-piral#34]
I pasted the following into my launch.json for VS Code.
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:1234",
            "webRoot": "${workspaceFolder}",
            "preLaunchTask": "pilet: debug"
        }
    ]
}
```
But the preLaunchTask seems to be waiting for `pilet debug` to finish before launching chrome. And since it's a debug watcher, it will never finish until I exit it. When I press ctrl+c in the debug terminal, chrome finally pops up, but the host is no longer running so I just get a ERR_CONNECTION_REFUSED.

Am I doing something wrong? :/

**Comment by FlorianRappl** [comment]
There is more to it - have you also added the `tasks.json`?

Look at the given patterns - they should match some of the console output.

**Comment by FlorianRappl** [comment]
Seems to be working fine on my end.

Setup:

1. Using a pilet with Piral 1.6.1
2. Using the latest version of the VS Code extension
3. On MacOS open VS Code
4. Use F5 to create a launch.json (select "Web App")
5. Change the content of the created launch.json to match the OP
6. Run the pilet using F5
7. Set a break point somewhere (e.g., in a page)
8. Navigate to the page; breakpoint is hit
