### ISSUE TITLE
Could not load the "package.json". Make sure the workspace is valid.

### ISSUE THREAD

**Issue by MotivatedCreation** [smapiot/vscode-piral#6]
**Problem**
The extensions is not able to load the workspace. In src/extension.ts on line 23, workspace.uri.path returns the path prefixed with '/'. 

**VS Code Error**
`Could not load the "package.json". Make sure the workspace is valid.`

**Potential Fix**
In src/extension.ts on line 23, replace `workspace.uri.path` with `workspace.uri.fsPath`.

**Platform**
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by FlorianRappl** [comment]
Thanks for digging into this early release - and also providing a fix for the issue!

Much appreciated :beers:

**Comment by FlorianRappl** [comment]
Landed in `develop`.
