### ISSUE TITLE
Create Piral / Pilet Command

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/vscode-piral#9]
Introduce a visual scaffold helper / page.

Could be similar to the one shown for [Rax VS Code Extension](https://github.com/raxjs/rax-vscode-extensions), specifically [create](https://github.com/raxjs/rax-vscode-extensions/tree/master/extensions/vscode-create-rax).

**Comment by iotcloudarchitect** [comment]
First version has been pushed to develop branch

**Comment by FlorianRappl** [comment]
Awsome!

**Comment by FlorianRappl** [comment]
Landed in `develop`.
